<template><div><h2 id="第1章-随机事件及其概率" tabindex="-1"><a class="header-anchor" href="#第1章-随机事件及其概率" aria-hidden="true">#</a> 第1章 随机事件及其概率</h2>
<h3 id="_1-1-随机事件" tabindex="-1"><a class="header-anchor" href="#_1-1-随机事件" aria-hidden="true">#</a> 1.1 随机事件</h3>
<h3 id="_1-2-概率" tabindex="-1"><a class="header-anchor" href="#_1-2-概率" aria-hidden="true">#</a> 1.2 概率</h3>
<h3 id="_1-3-条件概率" tabindex="-1"><a class="header-anchor" href="#_1-3-条件概率" aria-hidden="true">#</a> 1.3 条件概率</h3>
<h3 id="_1-4-独立性" tabindex="-1"><a class="header-anchor" href="#_1-4-独立性" aria-hidden="true">#</a> 1.4 独立性</h3>
<h2 id="第2章-随机变量及其分布" tabindex="-1"><a class="header-anchor" href="#第2章-随机变量及其分布" aria-hidden="true">#</a> 第2章 随机变量及其分布</h2>
<h3 id="_2-1-随机变量及其分布函数" tabindex="-1"><a class="header-anchor" href="#_2-1-随机变量及其分布函数" aria-hidden="true">#</a> 2.1 随机变量及其分布函数</h3>
<h3 id="_2-2-离散型随机变量及其分布律" tabindex="-1"><a class="header-anchor" href="#_2-2-离散型随机变量及其分布律" aria-hidden="true">#</a> 2.2 离散型随机变量及其分布律</h3>
<h3 id="_2-3-连续型随机变量及其概率密度" tabindex="-1"><a class="header-anchor" href="#_2-3-连续型随机变量及其概率密度" aria-hidden="true">#</a> 2.3 连续型随机变量及其概率密度</h3>
<h3 id="_2-4-随机变量的函数的分布" tabindex="-1"><a class="header-anchor" href="#_2-4-随机变量的函数的分布" aria-hidden="true">#</a> 2.4 随机变量的函数的分布</h3>
<h2 id="第3章-多维随机变量及其分布" tabindex="-1"><a class="header-anchor" href="#第3章-多维随机变量及其分布" aria-hidden="true">#</a> 第3章 多维随机变量及其分布</h2>
<h3 id="_3-1-二维随机变量" tabindex="-1"><a class="header-anchor" href="#_3-1-二维随机变量" aria-hidden="true">#</a> 3.1 二维随机变量</h3>
<h3 id="_3-2-边缘分布" tabindex="-1"><a class="header-anchor" href="#_3-2-边缘分布" aria-hidden="true">#</a> 3.2 边缘分布</h3>
<h3 id="_3-3-随机变量的独立性" tabindex="-1"><a class="header-anchor" href="#_3-3-随机变量的独立性" aria-hidden="true">#</a> 3.3 随机变量的独立性</h3>
<h3 id="_3-4-条件概率分布" tabindex="-1"><a class="header-anchor" href="#_3-4-条件概率分布" aria-hidden="true">#</a> 3.4 条件概率分布</h3>
<h3 id="_3-5-二维随机变量的函数的分布" tabindex="-1"><a class="header-anchor" href="#_3-5-二维随机变量的函数的分布" aria-hidden="true">#</a> 3.5 二维随机变量的函数的分布</h3>
<h2 id="第4章-数字特征" tabindex="-1"><a class="header-anchor" href="#第4章-数字特征" aria-hidden="true">#</a> 第4章 数字特征</h2>
<h3 id="_4-1-数学期望" tabindex="-1"><a class="header-anchor" href="#_4-1-数学期望" aria-hidden="true">#</a> 4.1 数学期望</h3>
<h3 id="_4-2-方差" tabindex="-1"><a class="header-anchor" href="#_4-2-方差" aria-hidden="true">#</a> 4.2 方差</h3>
<h3 id="_4-3-几种常见分布的期望与方差" tabindex="-1"><a class="header-anchor" href="#_4-3-几种常见分布的期望与方差" aria-hidden="true">#</a> 4.3 几种常见分布的期望与方差</h3>
<h3 id="_4-4-协方差、相关系数与矩" tabindex="-1"><a class="header-anchor" href="#_4-4-协方差、相关系数与矩" aria-hidden="true">#</a> 4.4 协方差、相关系数与矩</h3>
<h2 id="第5章-大数定律与中心极限定理" tabindex="-1"><a class="header-anchor" href="#第5章-大数定律与中心极限定理" aria-hidden="true">#</a> 第5章 大数定律与中心极限定理</h2>
<h3 id="_5-1-大数定律" tabindex="-1"><a class="header-anchor" href="#_5-1-大数定律" aria-hidden="true">#</a> 5.1 大数定律</h3>
<h3 id="_5-2-中心极限定理" tabindex="-1"><a class="header-anchor" href="#_5-2-中心极限定理" aria-hidden="true">#</a> 5.2 中心极限定理</h3>
<h2 id="第6章-数理统计的基本概念" tabindex="-1"><a class="header-anchor" href="#第6章-数理统计的基本概念" aria-hidden="true">#</a> 第6章 数理统计的基本概念</h2>
<h3 id="_6-1-样本与统计量" tabindex="-1"><a class="header-anchor" href="#_6-1-样本与统计量" aria-hidden="true">#</a> 6.1 样本与统计量</h3>
<h3 id="_6-2-经验分布函数与直方图" tabindex="-1"><a class="header-anchor" href="#_6-2-经验分布函数与直方图" aria-hidden="true">#</a> 6.2 经验分布函数与直方图</h3>
<h3 id="_6-3-抽样分布" tabindex="-1"><a class="header-anchor" href="#_6-3-抽样分布" aria-hidden="true">#</a> 6.3 抽样分布</h3>
<h2 id="第7章-参数估计" tabindex="-1"><a class="header-anchor" href="#第7章-参数估计" aria-hidden="true">#</a> 第7章 参数估计</h2>
<h3 id="_7-1-点估计" tabindex="-1"><a class="header-anchor" href="#_7-1-点估计" aria-hidden="true">#</a> 7.1 点估计</h3>
<h3 id="_7-2-估计量的评价标准" tabindex="-1"><a class="header-anchor" href="#_7-2-估计量的评价标准" aria-hidden="true">#</a> 7.2 估计量的评价标准</h3>
<h3 id="_7-3-区间估计" tabindex="-1"><a class="header-anchor" href="#_7-3-区间估计" aria-hidden="true">#</a> 7.3 区间估计</h3>
<h2 id="第8章-假设检验" tabindex="-1"><a class="header-anchor" href="#第8章-假设检验" aria-hidden="true">#</a> 第8章 假设检验</h2>
<h3 id="_8-1-假设检验的基本概念" tabindex="-1"><a class="header-anchor" href="#_8-1-假设检验的基本概念" aria-hidden="true">#</a> 8.1 假设检验的基本概念</h3>
<h3 id="_8-2-单个正态总体参数的假设检验" tabindex="-1"><a class="header-anchor" href="#_8-2-单个正态总体参数的假设检验" aria-hidden="true">#</a> 8.2 单个正态总体参数的假设检验</h3>
<h3 id="_8-3-两个正态总体参数的假设检验" tabindex="-1"><a class="header-anchor" href="#_8-3-两个正态总体参数的假设检验" aria-hidden="true">#</a> 8.3 两个正态总体参数的假设检验</h3>
<h3 id="_8-4-非参数假设检验" tabindex="-1"><a class="header-anchor" href="#_8-4-非参数假设检验" aria-hidden="true">#</a> 8.4 非参数假设检验</h3>
<h2 id="第9章-回归分析与方差分析" tabindex="-1"><a class="header-anchor" href="#第9章-回归分析与方差分析" aria-hidden="true">#</a> 第9章 回归分析与方差分析</h2>
<h3 id="_9-1-回归分析的一般概念" tabindex="-1"><a class="header-anchor" href="#_9-1-回归分析的一般概念" aria-hidden="true">#</a> 9.1 回归分析的一般概念</h3>
<h3 id="_9-2-一元线性回归" tabindex="-1"><a class="header-anchor" href="#_9-2-一元线性回归" aria-hidden="true">#</a> 9.2 一元线性回归</h3>
<h3 id="_9-3-多元线性回归" tabindex="-1"><a class="header-anchor" href="#_9-3-多元线性回归" aria-hidden="true">#</a> 9.3 多元线性回归</h3>
<h3 id="_9-4-单因素的方差分析" tabindex="-1"><a class="header-anchor" href="#_9-4-单因素的方差分析" aria-hidden="true">#</a> 9.4 单因素的方差分析</h3>
</div></template>
